Hw10 program optimization
dimazusov/hw-test pull request #11
Opened 2020-12-05 12:28 UTC by dimazusov

## Домашнее задание №10 «Оптимизация программы»

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-12-06 06:27 UTC, agneum commented
Рекомендую не коммитать файл с данными `hw10_program_optimization/testdata/users.dat`

2020-12-06 06:36 UTC, agneum requested changes
Спасибо за выполненное задание. Хорошая работа.
Есть критичные замечания, поэтому возвращаю на доработку.
Итого: 6 баллов из 10.

2020-12-06 06:36 UTC, agneum commented on hw10_program_optimization/stats.go
> +	domainStat := make(DomainStat, 700)
Почему 700 элементов?
Предлагаю вынести это значение в константу

2020-12-06 06:36 UTC, agneum commented on hw10_program_optimization/stats.go
> +	fullDomain := strings.ToLower(strings.SplitN(m.Email, "@", 2)[1])
В качестве альтернативы для определения домена можно использовать https://golang.org/pkg/strings/#HasSuffix

Если в поле Email будет отсутствовать `@`, то получим панику ` index out of range`
```
strings.SplitN(m.Email, "@", 2)[1]
```

2020-12-06 06:36 UTC, agneum commented on hw10_program_optimization/stats.go
> +	return strings.SplitN(fullDomain, ".", 2)[1] == domain
Аналогично, здесь потенциально будет паника.

Дополнительный вопрос: насколько необходимо отделять домен верхнего уровня при проверке?

2020-12-11 02:23 UTC, agneum commented on hw10_program_optimization/stats.go
> +	fullDomain := strings.ToLower(strings.SplitN(m.Email, "@", 2)[1])
После правки действительно будет работать, но суть проблемы остается: после получения слайса происходит сразу обращение к элементу по индексу. Этот элемент может отсутствовать, что приведёт к панике.

В данном случае нас спасает предварительная проверка `Contains`, но нет гарантий, что она всегда будет вызвана перед `SplitN`. Например, при рефакторинге или добавлении новой функциональности.

Более надёжно получить слайс в переменную, проверить его длину и после этого обратиться к элементу

2020-12-11 02:25 UTC, agneum submitted a review, later dismissed
Спасибо за правки. 
Большие файлы лучше всё-таки не коммитать, сейчас это можно исправить только с помощью push --force.
Итого: 9 баллов из 10.

2021-01-22 06:57 UTC, Antonboom approved these changes

2021-01-22 14:30 UTC, agneum approved these changes

2021-01-23 15:05 UTC, dimazusov commented
hw10

2021-01-23 15:47 UTC, merged