Hw11 telnet client
dimazusov/hw-test pull request #12
Opened 2020-12-13 14:15 UTC by dimazusov

2021-01-18 04:46 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/58245/8092/

Здравствуйте!
Аккуратная работа, но есть недоработки (всё по ТЗ) и нет новых тестов.

Предварительно
5 / 10

2021-01-18 04:46 UTC, Antonboom commented on hw09_struct_validator/README.md
> +## Домашнее задание №9 «Валидатор структур»
1) Почему вы не мержите остальные реквесты?
2) Почему вы бранчуете новое ДЗ от предыдущего, а не от master?

Усложняете жизнь преподаваталям!

2021-01-18 04:46 UTC, Antonboom commented on hw11_telnet_client/go.mod
>  go 1.14
1.15

2021-01-18 04:46 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	flag.StringVar(&timeout, "timeout", "", "timeout for connection closing")
DurationVar?

2021-01-18 04:46 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	if timeout != "" {
вы должны указать `default` у флага согласно ТЗ и ветка пропадёт

2021-01-18 04:46 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	err := client.Connect()
где вызов Close?

2021-01-18 04:46 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	wg.Wait()
Где обработка SIGINT?

2021-01-18 04:46 UTC, Antonboom commented on hw11_telnet_client/telnet/telnet_test.go
> +package telnet //nolint:golint,stylecheck
где новые тесты?

2021-01-19 20:35 UTC, dimazusov commented on hw09_struct_validator/README.md
> +## Домашнее задание №9 «Валидатор структур»
исправил, смержил все что смержилось,  остальное нужно одобрить, потому что после обновления невозможно смержить

2021-01-19 20:41 UTC, dimazusov commented on hw11_telnet_client/main.go
> +	flag.StringVar(&timeout, "timeout", "", "timeout for connection closing")
не понял, что именно имеется в виду?

2021-01-19 20:43 UTC, dimazusov commented on hw11_telnet_client/main.go
> +	err := client.Connect()
поправил

2021-01-19 21:51 UTC, dimazusov commented on hw11_telnet_client/main.go
> +	wg.Wait()
сделал

2021-01-20 04:02 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	flag.StringVar(&timeout, "timeout", "", "timeout for connection closing")
https://golang.org/pkg/flag/#DurationVar

2021-01-20 05:13 UTC, Antonboom approved these changes
Принято
8 / 10

2021-01-20 05:13 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	flag.StringVar(&timeout, "timeout", "10s", "timeout for connection closing")
https://golang.org/pkg/flag/#DurationVar

2021-01-20 05:13 UTC, Antonboom commented on hw11_telnet_client/main.go
> +		wg.Done()
сделать через defer на всякий пожарный?

2021-01-20 05:13 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	wg.Wait()
а нужно ли дожидаться этих горутин?

2021-01-20 05:13 UTC, Antonboom commented on hw11_telnet_client/main.go
> +	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
defer signal.Stop?

2021-01-20 17:50 UTC, merged