hw3
dimazusov/hw-test pull request #3
Opened 2020-10-10 18:07 UTC by dimazusov

## Домашнее задание №3 «Частотный анализ»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-10-12 06:55 UTC, Antonboom requested changes
Здравствуйте!
Интересно решение, но хотелось бы попроще и поаккуратнее.
Замечания и предложения привёл ниже.

Предварительно
7 / 10

2020-10-12 06:55 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +		return []string{}
return nil

2020-10-12 06:55 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +func splitTextToWords(text *string) map[string]int {
строки не стоит передавать через указатель, это и так plain-структура с указателем
https://github.com/golang/go/wiki/CodeReviewComments#pass-values

2020-10-12 06:55 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	re = regexp.MustCompile(`[,\.\";(!-):]|^\-$`)
- регулярки стоит вынести в var: тяжелая операция + Must может запаниковать
- одной регуляркой не обойтись?

2020-10-12 06:55 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	maxLenMostFreqWords := 12
что за магические числа?

2020-10-12 06:55 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	resMap := make(map[int][]string)
что за страсти с 12 по 42 строку?
очень сложно

вам всего лишь нужно:
- собрать слайс <слово, встречаемость>
- отсортировать по встречаемости
- вернуть первые 10

2020-10-18 12:06 UTC, dimazusov commented on hw03_frequency_analysis/top.go
> +func splitTextToWords(text *string) map[string]int {
сделал

2020-10-21 05:55 UTC, Antonboom approved these changes
Гораздо лучше!
Есть пара моментов, которые можно сделать приятнее.

Принято
8 / 10

2020-10-21 05:55 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +		if i >= maxCountMostRequreciesWords && !isNextWordHasSameCount(reqWords, i) {
лишнии проверки, достаточно сделать 
```golang
range reqWords[:maxCountMostRequreciesWords]
```

2020-10-21 05:55 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +		index, ok := findIndexByWord(mostRequrencyWords, replacableWord)
получили O(n^2)

почему не отображение слово-частота?

и вроде раньше была map'а

2020-10-29 20:52 UTC, merged