add hw04
dimazusov/hw-test pull request #4
Opened 2020-10-11 18:09 UTC by dimazusov

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-10-17 16:58 UTC, Antonboom requested changes
Здравствуйте!
Спасибо за работу, но требуется исправления.

Предварительно
5 / 10

2020-10-17 16:58 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +	Set(key string, value interface{}) bool
не используется тип Key

2020-10-17 16:58 UTC, Antonboom commented on hw04_lru_cache/cache_test.go
> +			c.Set(strconv.Itoa(i), i)
это здесь было не просто так

2020-10-17 16:58 UTC, Antonboom commented on hw04_lru_cache/list_funcs.go
> +package hw04_lru_cache //nolint:golint,stylecheck
такое разделение на файлы в целом не принято в Go, обычно методы лежат рядом с типом, к которому они относятся

2020-10-17 16:58 UTC, Antonboom commented on hw04_lru_cache/cache_test.go
> +		c := NewCache(5)
прочитайте подробнее ТЗ, данные тесты слишком тривиальные и не проверяют логики выталкивания из кэша

2020-10-17 16:58 UTC, Antonboom commented on hw04_lru_cache/cache_funcs.go
> +		for el := m.queue.Front(); el != nil; el = el.Next {
O(n), в ТЗ сказано, что все методы кэша должны работать за О(1)

внимательнее прочитайте алгоритм и посмотрите на структуру кэша

2020-10-18 17:07 UTC, dimazusov commented on hw04_lru_cache/cache_test.go
> +		c := NewCache(5)
66 строка, тест как раз проверяет что если мы создадим кэш с вместимостью 2 и добавим 3 элемента, то при первый получить уже не получится.

2020-10-19 16:15 UTC, Antonboom commented on hw04_lru_cache/cache_test.go
> +		c := NewCache(5)
еще раз: прочитайте, пожалуйста, алгоритм тестирования, описанный в ТЗ

вы так тестируете размер кэша, но не логику по перемещению элементов в очереди.

2020-10-19 16:17 UTC, Antonboom requested changes
Отлично, ещё немного исправлений и получим работающий кэш.

2020-10-19 16:17 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +	if wasInCache {
в любом случае был элемент или нет, должен случиться MoveToFront

текущая реализация неверная, и как раз не хватает теста, который бы это показал

2020-10-19 16:17 UTC, Antonboom commented on hw04_lru_cache/cache_test.go
> +		c := NewCache(5)
еще раз: прочитайте, пожалуйста, алгоритм тестирования, описанный в ТЗ

вы так тестируете размер кэша, но не логику по перемещению элементов в очереди.

2020-10-19 19:36 UTC, dimazusov commented on hw04_lru_cache/cache_test.go
> +		c := NewCache(5)
Прочитал еще раз, при получении добавил перемещение в начало, при добавлении тоже перемещение в начало.

2020-10-27 10:47 UTC, Antonboom approved these changes
Отличная работа!

Принято
10 / 10

2020-10-29 20:54 UTC, merged