add hw 5
dimazusov/hw-test pull request #5
Opened 2020-10-29 20:55 UTC by dimazusov

## Домашнее задание №5 «Параллельное исполнение»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-11-14 09:45 UTC, kulti requested changes
В решение есть одна ошибка. Предлагаю ее исправить. В остальном оно корректное.

При этом получилось немного сложно и не оптимально. Например, можно обойтись одним каналом и без буферизации.

Рекомендую посмотреть разбор этого ДЗ. Я его проводил после занятия про планировщик. Начало примерно на 1ч 26м.

2020-11-14 09:45 UTC, kulti commented on hw05_parallel_execution/run.go
>  	return nil
Если не будет ошибок, то тут выход из Run произойдет без ожидания завершения горутин. В тестах есть проверка на то, что остались незавершенные горутины. Чтобы убедится, что они и правда остаются можно добавить `defer time.Sleep(time.Second)` после `defer wg.Done()`.

2020-11-16 21:08 UTC, dimazusov commented on hw05_parallel_execution/run.go
>  	return nil
сделал, спасибо за замечание

2020-11-18 10:52 UTC, kulti approved these changes
Теперь решение корректное. ДЗ принято - 10/10.

2020-11-21 17:38 UTC, merged